anguage: node_js
node_js:
  - "10"
before_install:
 - npm install -g cnpm --registry=https://registry.npm.taobao.org
 install:
  -cnpm install
after_script:
  - npm run build
  - git config user.name "${USER_NAME}"
  - git config user.email "${USER_EMAIL}"
  - git add .
  - git commit -m "publish cheshi"
  - git push --force --quiet "https://${ACC_TOKEN}@${GH_REF}" master:${BRANCH}

branches:
  only:
    - main